# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/task_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TaskDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 350)
        Dialog.setMinimumSize(QtCore.QSize(400, 350))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(Dialog)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.title_edit = QtWidgets.QLineEdit(Dialog)
        self.title_edit.setObjectName("title_edit")
        self.verticalLayout.addWidget(self.title_edit)
        self.description_label = QtWidgets.QLabel(Dialog)
        self.description_label.setObjectName("description_label")
        self.verticalLayout.addWidget(self.description_label)
        self.description_edit = QtWidgets.QTextEdit(Dialog)
        self.description_edit.setObjectName("description_edit")
        self.verticalLayout.addWidget(self.description_edit)
        self.deadline_label = QtWidgets.QLabel(Dialog)
        self.deadline_label.setObjectName("deadline_label")
        self.verticalLayout.addWidget(self.deadline_label)
        self.deadline_edit = QtWidgets.QDateEdit(Dialog)
        self.deadline_edit.setObjectName("deadline_edit")
        self.verticalLayout.addWidget(self.deadline_edit)
        self.priority_label = QtWidgets.QLabel(Dialog)
        self.priority_label.setObjectName("priority_label")
        self.verticalLayout.addWidget(self.priority_label)
        self.priority_edit = QtWidgets.QSpinBox(Dialog)
        self.priority_edit.setObjectName("priority_edit")
        self.verticalLayout.addWidget(self.priority_edit)
        self.status_checkbox = QtWidgets.QCheckBox(Dialog)
        self.status_checkbox.setObjectName("status_checkbox")
        self.verticalLayout.addWidget(self.status_checkbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_button = QtWidgets.QPushButton(Dialog)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TaskDialog"))
        self.title_label.setText(_translate("Dialog", "Title:"))
        self.description_label.setText(_translate("Dialog", "Description:"))
        self.deadline_label.setText(_translate("Dialog", "Deadline:"))
        self.priority_label.setText(_translate("Dialog", "Priority:"))
        self.status_checkbox.setText(_translate("Dialog", "Completed"))
        self.save_button.setText(_translate("Dialog", "Save"))
        self.cancel_button.setText(_translate("Dialog", "Cancel"))
